trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=devsecopscherryorg -Dsonar.projectKey=azuredevopsdevsecopsprojectkey -Dsonar.login=6b4dd7ebae8a9a6c7784be287b35dde473b212ff
  displayName: "Integrate SAST using SonarCloud in Azure DevOps DevSecOps Pipeline"
